language: node_js
node_js:
  - 9

install:
  - npm install

script:
  - npm run build
  - npm run predeploy
  - npm run test

deploy:
  - provider: script
    script:
      - npx semantic-release
    github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    keep-history: true
    local-dir: example/build
    github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
    on:
      branch: master